---
- name: Using ServiceNow Collection
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - servicenow.servicenow

  tasks:
  - name: Install snow python package
    pip:
      name: pysnow
    
  - name: load vars for use in incident
    include_vars: password.yaml
  - name: Create an incident
    snow_record:
      username: "admin"
      password: "{{ sn_password }}"
      instance: "dev59613"
      state: present
      data:
        short_description: "This is a test incident opened by Ansible - Part deux"
        severity: "2"
        priority: "2"
        assigned_to: "abraham.lincoln"
        assignment_group: "US Presidents Group 2"
    register: new_incident
    #delegate_to: localhost
  - debug:
          var: new_incident.record.number
