---
- name: Install the apache web service
  hosts: webservers
  become: yes
  collections:
    - servicenow.servicenow

  tasks:
    #- name: load vars for use in incident
    #  include_vars: change_request_vars.yaml
    - name: load password vars for use in incident
      include_vars: password.yaml

    - name: install apache
      yum:
        name: httpd
        state: present

    - name: start httpd
      ignore_errors: yes
      service:
        name: httpd
        state: started        
      register: app      
    #- debug:
    #      var: app

    - name: Create an incident
      snow_record:
        username: "admin"
        password: "{{ sn_password }}"
        instance: "dev63304"
        state: present
        data:
          short_description: "This is a test incident opened by Ansible - {{ ansible_hostname }}"
          severity: "2"
          priority: "2"
          assigned_to: "abraham.lincoln"
          assignment_group: "US Presidents Group 2"
          work_notes: "from {{ ansible_hostname }}"
      register: new_incident
      when: app is failed
      delegate_to: tower1.1b24.internal
    - debug:
            var: new_incident.record.number
      when: app is failed
